league_tutorial/config/routes.rb
LeagueTutorial::Application.routes.draw do
  resources :teams


  resources :clubs, :except => [:new, :edit]
  resources :teams, :except => [:new, :edit]
end

league_tutorial/app/models/club.rb
class Club < ActiveRecord::Base
  attr_accessible :contact_officer, :date_created, :name
end

league_tutorial/app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :club
  attr_accessible :captian, :date_created, :name
end

league_tutorial/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

league_tutorial/app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_filter :intercept_html_requests
  layout false
  respond_to :json

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = Club.all
    render json: @clubs
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
    @club = Club.find(params[:id])

    render json: @club
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = Club.new(params[:club])

    if @club.save
      render json: @club, status: :created, location: @club
    else
      render json: @club.errors, status: :unprocessable_entity
    end
  end

  # PUT /clubs/1
  # PUT /clubs/1.json
  def update
    @club = Club.find(params[:id])

    if @club.update_attributes(params[:club])
      head :no_content
    else
      render json: @club.errors, status: :unprocessable_entity
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club = Club.find(params[:id])
    @club.destroy

    head :no_content
  end

  private
  def intercept_html_requests
    redirect_to('/') if request.format == Mime::HTML
  end
end

league_tutorial/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = Team.find(params[:id])
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

league_tutorial/app/helpers/application_helper.rb
module ApplicationHelper
end

league_tutorial/app/helpers/clubs_helper.rb
module ClubsHelper
end

league_tutorial/app/helpers/teams_helper.rb
module TeamsHelper
end

league_tutorial/app/views/clubs/_form.html.erb
<%= form_for(@club) do |f| %>
  <% if @club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% @club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact_officer %><br />
    <%= f.text_field :contact_officer %>
  </div>
  <div class="field">
    <%= f.label :date_created %><br />
    <%= f.datetime_select :date_created %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

league_tutorial/app/views/clubs/edit.html.erb
<h1>Editing club</h1>

<%= render 'form' %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

league_tutorial/app/views/clubs/index.html.erb
<h1>Listing clubs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Contact officer</th>
    <th>Date created</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clubs.each do |club| %>
  <tr>
    <td><%= club.name %></td>
    <td><%= club.contact_officer %></td>
    <td><%= club.date_created %></td>
    <td><%= link_to 'Show', club %></td>
    <td><%= link_to 'Edit', edit_club_path(club) %></td>
    <td><%= link_to 'Destroy', club, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Club', new_club_path %>

league_tutorial/app/views/clubs/new.html.erb
<h1>New club</h1>

<%= render 'form' %>

<%= link_to 'Back', clubs_path %>

league_tutorial/app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @club.name %>
</p>

<p>
  <b>Contact officer:</b>
  <%= @club.contact_officer %>
</p>

<p>
  <b>Date created:</b>
  <%= @club.date_created %>
</p>


<%= link_to 'Edit', edit_club_path(@club) %> |
<%= link_to 'Back', clubs_path %>

league_tutorial/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeagueTutorial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>